[package]
name = "untitled"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = { version = "0.11.8" }
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["v4"] }
anyhow = "1.0"
futures = "0.3"
pretty_env_logger = "0.5"